### ISSUE TITLE
Discussion: Updates with NEMO information to SU2 webpage

### ISSUE THREAD

**Issue by jtneedels** [su2code/su2code.github.io#107]
Hi everyone,

I'd like to work on adding details about the NEMO solver to the online documentation, starting with relevant details on theory & solver. I haven't worked in this repo before, so want to make sure I understand the philosophy before branching and making too many edits. 

Would it make sense to add a set of governing equations for NEMO (hypersonic reacting flows) since these are different from e.g. compressible Navier-Stokes, or should that information go somewhere else? Thanks!

**Comment by WallyMaier** [comment]
I started a branch a while back (I just pushed the little changes I added), and I just followed the solver structure (EULER/INC_EULER/NEMO_EULER) since we do solve different equations.  Feel delete the branch if its not helpful.

**Comment by jtneedels** [comment]
Ah glad I checked! Okay great, that's what I had in mind, I'll just add some edits to your branch then if that's okay with you @WallyMaier.

**Comment by WallyMaier** [comment]
Go for it!
