### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by malteyp** [su2code/su2code.github.io#5]
Hello,
I saw 2 dead links in the Documentation (in the file : su2code.github.io/blob/master/_docs/FAQ.md ).

* https://su2code.github.io/docs/QuickStart -> https://su2code.github.io/docs/Quick**-**Start
* https://github.com/su2code/SU2/blob/master/config_template_basic.cfg -> I didn't see a new link for this file.

Sincerely,

Pierre Maltey

**Comment by talbring** [comment]
Thanks! I fixed that.
